config/routes.rb
Rails.application.routes.draw do
  root 'images#index'

  resources :images, only: [:index, :show, :new, :create]
  post 'similar_images', to: 'images#get_similar_images', as: :similar_images
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/image.rb
require 'elasticsearch/model'

class Image < ApplicationRecord
  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks

  mount_uploader :image, ImageUploader

  validates_presence_of :image

  index_name "images-#{Rails.env}"

  settings do
    mappings dynamic: 'false' do
      indexes :text, type: :text, analyzer: 'english'
    end
  end

  DISTANCE_THRESHOLD = 25

  def self.search_text(query)
    Image.search(query)
  end

  def self.open_image(file)
    MiniMagick::Image.open(file)
  end

  def self.run_ocr(file)
    RTesseract.new(file)
  end

  def self.run_idhash(file)
    DHashVips::IDHash.fingerprint(file) if file.present?
  end

  def self.similar_images?(hash1, hash2)
    DHashVips::IDHash.distance(hash1, hash2) < DISTANCE_THRESHOLD
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  include CarrierWave::MiniMagick

  before_action :set_image, only: [:show]

  def index
    ids = Image.search_text(params[:search_text]).records.pluck(:id) unless params[:search_text].blank?
    search_params = { 
      extension: params[:search_format]&.upcase&.strip,
      width: params[:search_width]&.strip,
      height: params[:search_height]&.strip,
      id: ids
    }.reject { |k, v| v.blank? }
    
    if params[:search_text].present? && ids.blank?
      @images = []
    elsif params[:search_text].present? || search_params.present?
      @images = Image.where(search_params)
    else
      @images = Image.all
    end
  end

  def show
  end

  def get_similar_images
    hash = Image.run_idhash(params[:image]&.path)
    ids = Image.all.to_a.filter { |image| Image.similar_images?(hash, image.idhash.to_i) }.map(&:id)
    @images = Image.find(ids)
  end

  def new
    @image = Image.new
  end

  def create
    @image = Image.new(image_params)

    respond_to do |format|
      if @image.save
        path = @image.image.file.file
        current_image = Image.open_image(path)
        ocr = Image.run_ocr(path)
        idhash = Image.run_idhash(path)

        @image.update(
          width: current_image[:width],
          height: current_image[:height],
          extension: current_image[:format],
          text: ocr.to_s.split("\n").join(" ").delete("\f"),
          idhash: idhash.to_s
        )

        format.html { redirect_to @image, notice: 'Image was successfully created.' }
        format.json { render :show, status: :created, location: @image }
      else
        format.html { render :new }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    def set_image
      @image = Image.find(params[:id])
    end

    def image_params
      params.require(:image).permit(:image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/images/_form.html.erb
<%= form_with(model: image, local: true) do |form| %>
  <% if image.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(image.errors.count, "error") %> prohibited this image from being saved:</h2>

      <ul>
        <% image.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/images/get_similar_images.html.erb
<table>
  <thead>
    <tr>
      <th>Image</th>
      <th>Width</th>
      <th>Height</th>
      <th>Extension</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @images.each do |image| %>
      <tr>
        <td><%= image.image %></td>
        <td><%= image.width %></td>
        <td><%= image.height %></td>
        <td><%= image.extension %></td>
        <td><%= link_to 'Show', image %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Back', images_path %>

app/views/images/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Images</h1>

<h4>Search by image characteristic</h4>

  <%= form_with(url: images_path, local: true, method: :get) do |form| %>
    <div class="field">
      <%= form.label :file_format %>
      <%= form.text_field :search_format %>
    </div>

    <div class="field">
      <%= form.label :width %>
      <%= form.text_field :search_width %>
    </div>

    <div class="field">
      <%= form.label :height %>
      <%= form.text_field :search_height %>
    </div>    
    
    <div class="field">
      <%= form.label :text_search %>
      <%= form.text_field :search_text %>
    </div>
    
    <div class="actions">
      <%= form.submit "Search" %>
    </div>
  <% end %>

  <br>
  <br>

  <%= form_with(url: similar_images_path, local: true) do |form| %>
    <div class="field">
      <%= form.label :get_similar_images %>
      <%= form.file_field :image %>
    </div>
    
    <div class="actions">
      <%= form.submit "Search" %>
    </div>
  <% end %>
  
  <br>
  <br>

  <table>
    <thead>
      <tr>
        <th>Image</th>
        <th>Width</th>
        <th>Height</th>
        <th>Extension</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @images.each do |image| %>
        <tr>
          <td><%= image.image %></td>
          <td><%= image.width %></td>
          <td><%= image.height %></td>
          <td><%= image.extension %></td>
          <td><%= link_to 'Show', image %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

<br>

<%= link_to 'New Image', new_image_path %>

app/views/images/new.html.erb
<h1>New Image</h1>

<%= render 'form', image: @image %>

<%= link_to 'Back', images_path %>

app/views/images/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Image:</strong>
  <%= image_tag(@image.image.url) %>
</p>

<p>
  <strong>Width:</strong>
  <%= @image.width %>
</p>

<p>
  <strong>Height:</strong>
  <%= @image.height %>
</p>

<p>
  <strong>Format:</strong>
  <%= @image.extension %>
</p>

<%= link_to 'Back', images_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ImageRepo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>